### ISSUE TITLE
Bot is private

### ISSUE THREAD

**Issue by Deadpulse** [SpartanPlume/Tosurnament#20]
I'm having an error adding the bot to the server
discord says only the bot owner can add it

**Comment by SpartanPlume** [comment]
Oh sorry, I'm fixing that ASAP.

**Comment by SpartanPlume** [comment]
It should be fixed. Can you try again ?

**Comment by Deadpulse** [comment]
fixed now thanks for doing it quickly :D

**Comment by SpartanPlume** [comment]
No problem ^^
