### ISSUE TITLE
Some problems with usage

### ISSUE THREAD

**Issue by TheEZIC** [SpartanPlume/Tosurnament#28]
I did all items from tutorial V2. I try to ;result_match, but get cross emote on my massage without any error message from bot (same on ;reschedule command). It's the main reason why I create this issue, couse I can't debug it.
But, if I try to change referee or commentator it`s work currect.
My player sheet:
![image](https://user-images.githubusercontent.com/35061249/89744265-e5f10300-dab3-11ea-845a-4a9c4a3e75fd.png)
My schedule sheet:
![image](https://user-images.githubusercontent.com/35061249/89744292-294b7180-dab4-11ea-9cb6-3bde4e1079de.png)

**Comment by SpartanPlume** [comment]
Thanks for trying Tosurnament!
I fixed the error for the `;post_result` command. There was a problem with some error messages that has been fixed, but your problem with the reschedule command is `TeamNotFound: Hybrid Rainbow`.
If you prefer, you can contact me on Discord (`Spartan Plume#5172`) to check what could be the issue.

**Comment by SpartanPlume** [comment]
Fixed with last commits
