### ISSUE TITLE
Do not show bracket name in get_matches command if there is only 1 bracket

### ISSUE THREAD

**Issue by SpartanPlume** [SpartanPlume/Tosurnament#40]
The bracket name is the same than the tournament name in 1 bracket tournament, so it should not be shown as it will duplicate the information.

**Comment by NezzarClp** [comment]
Will you consider PR for this issue/repo?

**Comment by SpartanPlume** [comment]
Sure, you can make a PR for anything and I'll take a look. You can also create issues for new features if you want.
